
server:
  port: 8761
spring:
  application:
    name: provider
#eureka:
#  instance:
#    instance-id: provider-01
#    prefer-ip-address: true
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8760/eureka/

authencation_url: http://localhost:8089
security:
  oauth2:
#    userAuthorizationUri: http://localhost:8088/oauth/authorize
#    client:
#      access-token-uri: ${authencation_url}/oauth/token
#      client-id: web
#      client-secret: web
#      token-name: token
    resource:
      user-info-uri: ${authencation_url}/user
      prefer-token-info: false
