
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ds1?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 2016
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 192.168.132.213
    port: 6379

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user
      prefer-token-info: false
server:
  port: 8089
logging:
  level.com.yxj.eurekaoauth2.mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true


