
server:
  port: 8764
spring:
  application:
    name: zuul-gateway
eureka:
  instance:
    instance-id: zuul
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
zuul:
  routes:
    api:
      serviceId: provider
      path: /my-provider/**