
server:
  port: 8762
spring:
  application:
    name: provider
eureka:
  instance:
    hostname: localhost
    instance-id: provider-02
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/